apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: existing-vpc-cluster
  region: ap-northeast-1
  tags:
    karpenter.sh/discovery: ${EKS_CLUSTER_NAME}

iam:
  withOIDC: true
  podIdentityAssociations:
  - namespace: kube-system
    serviceAccountName: karpenter
    roleName: ${EKS_CLUSTER_NAME}-karpenter
    permissionPolicyARNs:
    - arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:policy/KarpenterControllerPolicy-${EKS_CLUSTER_NAME}
iamIdentityMappings:
- arn: "arn:aws:iam::134043038670:role/KarpenterNodeRole-${EKS_CLUSTER_NAME}"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent # not default addon
vpc:
  subnets:
    private:
      ap-northeast-1a: { id: ${PRIVATE_IPV6_SUBNET_ID_A} }
      ap-northeast-1c: { id: ${PRIVATE_IPV6_SUBNET_ID_C} }
      ap-northeast-1d: { id: ${PRIVATE_IPV6_SUBNET_ID_D} }
managedNodeGroups:
  - name: default
    amiFamily: Bottlerocket
    spot: true
    instanceTypes:
    - m5.large
    - m5a.large
    - m6a.large
    - m6i.large
    - m7a.large
    - m7i.large
    desiredCapacity: 2
    minSize: 0
    maxSize: 6
    privateNetworking: true