AWSTemplateFormatVersion: 2010-09-09
Description: Sample for demo

Parameters:
  S3BucketName:
    Description: S3 bucket name
    Type: String

  DynamoDBTableName:
    Description: DynamoDB table name
    Type: String

Resources:
  MyBucket:
    Type : AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
            BucketKeyEnabled: true
    DeletionPolicy: Delete

  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "MyPartitionKey"
          AttributeType: "S"
        - AttributeName: "MySortKey"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "MyPartitionKey"
          KeyType: "HASH"
        - AttributeName: "MySortKey"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref DynamoDBTableName
    DeletionPolicy: Delete

Outputs:
  BucketArn:
    Value: !GetAtt MyBucket.Arn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", BucketArn ] ]
