apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-ipv6
  region: ap-northeast-1
kubernetesNetworkConfig:
  ipFamily: IPv6 # Enable auto-assign IPv6 address in subnet settings
iam:
  withOIDC: true
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

vpc:
  subnets:
    private:
      ap-northeast-1a: { id: ${PRIVATE_IPV6_SUBNET_ID_A} }
      ap-northeast-1c: { id: ${PRIVATE_IPV6_SUBNET_ID_C} }
managedNodeGroups:
  - name: default
    amiFamily: Bottlerocket
    spot: true
    instanceTypes:
    - m5.large
    - m5a.large
    - m6a.large
    - m6i.large
    - m7a.large
    - m7i.large
    desiredCapacity: 2
    minSize: 0
    maxSize: 6
    privateNetworking: true
