version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-apigw-function-sqs-ddb-xray"
#s3_bucket = ""
s3_prefix = "sam-apigw-function-sqs-ddb-xray"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "ApiGwStage=\"Dev\""
