version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo-ddb-wit-lambda-test"
# s3_bucket = "YOUR_BUCKET"
s3_prefix = "sam-demo-ddb-with-lambda-test"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
