AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-apigw-lambda-canary

  Sample SAM Template for sam-apigw-lambda-canary

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    # TODO 複数のステージ作成とステージ変数で Lambda 関数の ARN指定
    Properties:
      StageName: dev
      Variables:
        lambda_alias: dev # 統合リクエストの指定がSAMだとできないので、Lambda関数のARNにステージ変数の組み込みができないぽい
      EndpointConfiguration:
        Type: REGIONAL
      OpenApiVersion: 3.0.3 # To delete default 'Stage' stage made by SAM # https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-openapiversion
  CloudWatchEvidentlyFeatureFlag:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/cwevidently/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Index:
          Type: Api
          Properties:
            Path: /cwevidently
            Method: get
            RestApiId:
              Ref: RestApi
      AutoPublishAlias: dev
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        ### 追加のインラインポリシーになる
        - Statement:
          - Sid: "EvaluateFeature"
            Effect: "Allow"
            Action:
              - "evidently:EvaluateFeature"
            Resource: "*"
  AppConfigFeatureFlag:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/appconfigfeature/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Index:
          Type: Api
          Properties:
            Path: /appconfigfeature
            Method: get
            RestApiId:
              Ref: RestApi
      AutoPublishAlias: dev
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        ### 追加のインラインポリシーになる
        - Statement:
          - Sid: "getAppconfig"
            Effect: "Allow"
            Action:
              - "appconfig:StartConfigurationSession"
              - "appconfig:GetLatestConfiguration"
            Resource: "*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CloudWatchEvidentlyFeatureFlagApi:
    Description: "API Gateway endpoint URL for dev stage for CloudWatchEvidentlyFeatureFlag"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/cwevidently"
  AppConfigFeatureFlagApi:
    Description: "API Gateway endpoint URL for dev stage for AppConfigFeatureFlag"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/appconfigfeature"
